# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for ShopReply Backend
#
# Usage:
#   pyinstaller shopreply.spec
#
# Or use build_exe.py which handles icon generation + this spec automatically.

import os

block_cipher = None

a = Analysis(
    ['tray_app.py'],
    pathex=[os.path.abspath('.')],
    binaries=[],
    datas=[
        ('.env.example', '.'),
    ],
    hiddenimports=[
        # --- uvicorn internals (not auto-detected) ---
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # --- FastAPI / Starlette ---
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        # --- App modules (same directory) ---
        'main',
        'database',
        'embeddings',
        'ollama_client',
        'schemas',
        # --- ML / Embedding ---
        'sentence_transformers',
        'torch',
        'transformers',
        'tokenizers',
        'huggingface_hub',
        # --- Data / DB ---
        'numpy',
        'sqlite3',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        # --- Tray ---
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        # --- HTTP ---
        'httpx',
        'httpcore',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        # --- Misc ---
        'pydantic',
        'dotenv',
        'h11',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ShopReply-Backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,          # No console window — tray icon only
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',        # Generated by build_exe.py
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ShopReply-Backend',
)
